debug: false

server:
  port: 8082

security:
  basic:
    enabled: true
  user:
    name: user
    password: password

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true